### ISSUE TITLE
module 'urllib.parse' has no attribute '_splittype'

### ISSUE THREAD

**Issue by arman-ku** [C0D3D3V/Moodle_Downloader_2#23]
Running main.py throws this:
```
Error:module 'urllib.parse' has no attribute '_splittype'
xxx.pdf   Traceback (most recent call last):
  File "/mnt/c/xxx/md2/download_service/url_target.py", line 185, in download
    reporthook=self.add_progress)
  File "/mnt/c/xxx/md2/download_service/url_target.py", line 215, in urlretrieve
    url_type, path = urlparse._splittype(url)
AttributeError: module 'urllib.parse' has no attribute '_splittype'

Error:module 'urllib.parse' has no attribute '_splittype'
```
The log basically reads the same.
running Ubuntu 18.04.4 LTS on Windows Subsystem for Linux
Python3 3.6.9
Python 2.7.17

Any Ideas?

**Comment by C0D3D3V** [comment]
I made an update that should solve the problem, but you should also update your Python if possible :) There is Python 3.8 available

**Comment by arman-ku** [comment]
Thank you!
